[package]
name = "mathematica_examples"
version = "0.1"
lean_version = "leanprover-community/lean:3.18.4"
path = "src"

[dependencies]
mathematica = {git = "https://github.com/rlewis1988/mathematica", rev = "1324ab17aca442da09daec4fc3277420a0fb67bb"}
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "15cacf0ea137bb0ad9120a4489ead0cf13c0a81d"}
